highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://gopikakini.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Gopika Kini's Resume
name: Gopika Kini
email: gopikagkini@gmail.com
email_full: mailto:gopikagkini@gmail.com
website: github.io/gopikakini
website_full: https://gopikakini.github.io
github: trending
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: 
  postcode: 
  city: Bangalore
  country: India
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
